version: "3.7"
services:
  koonetto_blog_postgres:
    image: postgres:14.11-alpine3.18
    container_name: koonetto_blog_postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=neko
      - POSTGRES_PASSWORD=miaw
      - POSTGRES_DB=koonetto_blog_postgres
    volumes:
      - koonetto-blog-data-slaves:/var/lib/postgresql/data

  koonetto_blog_redis:
    image: redis:7.4.0-alpine
    container_name: koonetto_blog_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  koonetto-blog-data-slaves: