spring:
  application:
    name: koneetto-blog
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/koonetto_blog_postgres
    username: neko
    password: miaw
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    baseline-version: 1
    enabled: true
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
      database: 0
      timeout: 5s
      connect-timeout: 10s

  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: 'cache:'
      cache-null-values: true
      enable-statistics: true
      time-to-live: 60s